"""Fetch the official participant kit and wire Converge into it.

The competition requires that results are produced by the **unmodified** official
evaluator. So this repository never vendors the organizer's code or data: it
clones the participant repository into ``.kit/``, downloads the frozen catalog
from the published release, verifies its SHA256, and drops in a three-line shim
that makes ``starter.agent.Agent`` resolve to :class:`converge.agent.Agent`.

Usage::

    python tools/bootstrap.py                 # clone + download (needs network)
    python tools/bootstrap.py --from PATH     # reuse a kit you already have
"""

from __future__ import annotations

import argparse
import gzip
import hashlib
import shutil
import subprocess
import sys
import urllib.request
from pathlib import Path

REPO = "https://github.com/TechJam2026/techjam-conversational-search.git"
RELEASE = (
    "https://github.com/TechJam2026/techjam-conversational-search/releases/download/"
    "participant-kit"
)
CATALOG_SHA256 = "07fd142631fd6b03e2b4d09988c3eb7d53720e9d57010c79db48eeaada50a8f8"

ROOT = Path(__file__).resolve().parents[1]
KIT = ROOT / ".kit"

SHIM = '''"""Auto-generated by tools/bootstrap.py -- do not edit.

Redirects the official harness entry point to the Converge agent so the
evaluator can run completely unmodified.
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from converge.agent import Agent  # noqa: E402,F401
'''


def _run(*command: str) -> None:
    subprocess.run(command, check=True)


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1 << 20), b""):
            digest.update(chunk)
    return digest.hexdigest()


def fetch_kit(source: Path | None) -> None:
    if KIT.exists():
        print(f"kit already present at {KIT}")
        return
    if source is not None:
        print(f"copying kit from {source}")
        shutil.copytree(source, KIT, ignore=shutil.ignore_patterns(".git", "kit", "results*.json"))
        return
    print(f"cloning {REPO}")
    _run("git", "clone", "--depth", "1", REPO, str(KIT))


def fetch_catalog() -> None:
    catalog = KIT / "data" / "catalog.jsonl"
    if catalog.exists():
        print(f"catalog already present ({catalog.stat().st_size / 1e6:.1f} MB)")
        return
    archive = KIT / "data" / "catalog.jsonl.gz"
    if not archive.exists():
        url = f"{RELEASE}/catalog.jsonl.gz"
        print(f"downloading {url}")
        urllib.request.urlretrieve(url, archive)
    digest = _sha256(archive)
    if digest != CATALOG_SHA256:
        raise SystemExit(f"catalog checksum mismatch: {digest}")
    print("checksum verified; decompressing")
    with gzip.open(archive, "rb") as source, catalog.open("wb") as target:
        shutil.copyfileobj(source, target)


def install_shim() -> None:
    target = KIT / "starter" / "agent.py"
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(SHIM, encoding="utf-8")
    print(f"wired {target} -> converge.agent.Agent")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--from", dest="source", default=None,
                        help="reuse an already-downloaded participant kit")
    args = parser.parse_args()
    fetch_kit(Path(args.source).resolve() if args.source else None)
    fetch_catalog()
    install_shim()
    print("\nready:  python tools/run_eval.py")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
